CREATE TABLE `sy_application` (
  `APP_ID` varchar(40) NOT NULL COMMENT '应用ID',
  `APP_PARENTID` varchar(40) DEFAULT NULL COMMENT '上级应用ID',
  `APP_NAME` varchar(32) NOT NULL COMMENT '应用名称',
  `APP_TITLE` varchar(256) DEFAULT NULL COMMENT '应用标题',
  `APP_WEBPATH` varchar(128) NOT NULL COMMENT '应用路径',
  `APP_COMMENT` varchar(1000) DEFAULT NULL COMMENT '应用描述',
  `APP_BUILD_DATE` datetime NOT NULL COMMENT '应用部署时间',
  `APP_STATUS` varchar(1) NOT NULL COMMENT '应用状态 1可用 0不可用',
  `APP_TYPE` varchar(1) NOT NULL DEFAULT '0' COMMENT '应用类型(0 普通应用/1 系统应用)',
  PRIMARY KEY (`APP_ID`),
  KEY `APPNAME_UNIQUE_INDEX` (`APP_NAME`) USING BTREE,
  KEY `APPPATH_INDEX` (`APP_WEBPATH`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='应用表'
