CREATE TABLE `sy_menu` (
  `menu_id` VARCHAR(32) NOT NULL COMMENT '菜单ID',
  `menu_parentid` VARCHAR(32) DEFAULT NULL COMMENT '父级菜单ID',
  `menu_seq` BIGINT(16) DEFAULT NULL,
  `menu_index` INT(8) DEFAULT NULL COMMENT '排序序号',
  `menu_title` VARCHAR(64) DEFAULT NULL COMMENT '菜单标题',
  `menu_title_lang_id` VARCHAR(32) DEFAULT NULL COMMENT '对应国际化资源langId',
  `menu_path` VARCHAR(1024) DEFAULT NULL COMMENT '菜单路径',
  `menu_icon` VARCHAR(64) DEFAULT NULL COMMENT '菜单图标',
  `menu_kind` VARCHAR(32) DEFAULT NULL COMMENT '菜单类型',
  `obj_id` VARCHAR(40) DEFAULT NULL,
  `obj_path` VARCHAR(256) DEFAULT NULL COMMENT '权限项路径',
  `obj_app_name` VARCHAR(32) DEFAULT NULL COMMENT '权限项应用ID',
  `menu_app_name` VARCHAR(32) DEFAULT NULL COMMENT '菜单应用ID',
  `menu_state` VARCHAR(2) DEFAULT '01' COMMENT '菜单状态:01正常,02删除',
  `action_app_context` VARCHAR(32) DEFAULT NULL,
  `action_authorized` VARCHAR(1) DEFAULT 'F' COMMENT '授权项,default=''F''',
  `action_normal` VARCHAR(1) DEFAULT 'T' COMMENT '普通项,default=''T''',
  `action_systemic` VARCHAR(1) DEFAULT 'F' COMMENT '系统项,default=''F''',
  `action_safe` VARCHAR(1) DEFAULT 'F' COMMENT '安全项,default=''F''',
  `action_audit` VARCHAR(1) DEFAULT 'F' COMMENT '审计项,default=''F''',
  `open_position` INT(2) DEFAULT '1' COMMENT '是否在新窗口打开, 1：否 ；2：是',
  PRIMARY KEY (`menu_id`),
  KEY `MENUPARENTID_INDEX` (`menu_parentid`) USING BTREE
) ENGINE=INNODB DEFAULT CHARSET=utf8