CREATE TABLE `sy_permission_extend` (
  `PER_EX_ID` VARCHAR(40) NOT NULL COMMENT '属性扩展ID',
  `PERMISSION_ID` VARCHAR(40) NOT NULL COMMENT '权限ID',
  `ATTR_CODE` VARCHAR(32) NOT NULL COMMENT '属性编码',
  `ATTR_VALUE` VARCHAR(128) NOT NULL COMMENT '属性值',
  `TENANT_ID` VARCHAR(38) NOT NULL DEFAULT 'LSPT' COMMENT '租户ID',
  PRIMARY KEY (`PER_EX_ID`,`TENANT_ID`),
  KEY `idx_permission_code_value` (`PERMISSION_ID`,`ATTR_CODE`,`ATTR_VALUE`) USING BTREE
) ENGINE=INNODB DEFAULT CHARSET=utf8 COMMENT='权限属性扩展表'