CREATE TABLE `sy_param_sort` (
  `PARAM_SORT_ID` varchar(32) NOT NULL COMMENT '参数分类标识',
  `P_PARAM_SORT_CODE` varchar(32) DEFAULT NULL COMMENT '上级分类标识',
  `PARAM_SORT_CODE` varchar(32) NOT NULL COMMENT '参数分类编码',
  `PARAM_SORT_NAME` varchar(256) NOT NULL COMMENT '参数分类名称',
  `PARAM_SORT_DESC` varchar(256) DEFAULT NULL COMMENT '参数分类说明',
  `PARAM_SORT_CREATETIME` datetime DEFAULT NULL COMMENT '参数分类设置时间',
  `SEQUENCE` int(8) NOT NULL DEFAULT '0' COMMENT '分类排序',
  PRIMARY KEY (`PARAM_SORT_ID`),
  KEY `AK_Key_2` (`PARAM_SORT_CODE`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8