CREATE TABLE `sy_permission` (
  `PERMISSION_ID` varchar(40) NOT NULL COMMENT '权限ID',
  `APP_ID` varchar(40) NOT NULL COMMENT '应用ID',
  `PERMISSION_PARENTID` varchar(40) DEFAULT NULL COMMENT '上级权限ID',
  `PERMISSION_NAME` varchar(32) NOT NULL COMMENT '权限名称',
  `PERMISSION_CODE` varchar(32) NOT NULL COMMENT '权限编码',
  `PERMISSION_TYPE` varchar(1) NOT NULL COMMENT '权限类型 1WebFolder 2WebPage 3WebMethod 4WebTabPage 5WebButton',
  `PERMISSION_PATH` varchar(128) NOT NULL COMMENT '权限路径',
  `PERMISSION_STATUS` varchar(1) NOT NULL COMMENT '权限状态 1可用 0不可用',
  `PERMISSION_INDEX` varchar(16) DEFAULT NULL COMMENT '权限索引',
  `PERMISSION_COMMENT` varchar(256) DEFAULT NULL COMMENT '权限备注',
  `AUTH_ID` varchar(40) DEFAULT NULL COMMENT '同步amber1的AUTH_ID字段',
  PRIMARY KEY (`PERMISSION_ID`),
  KEY `UK_APPID_PERMISSIONCODE` (`APP_ID`,`PERMISSION_CODE`) USING BTREE,
  KEY `UK_APPID_PERMISSIONPATH` (`APP_ID`,`PERMISSION_PATH`) USING BTREE,
  KEY `idx_PERMISSION_PARENTID` (`PERMISSION_PARENTID`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='权限表'