
CREATE TABLE `sy_role` (
  `ROLE_ID` varchar(40) NOT NULL COMMENT '角色ID',
  `APP_ID` varchar(40) DEFAULT NULL COMMENT '应用ID',
  `ROLE_NAME` varchar(32) NOT NULL COMMENT '角色名称',
  `ROLE_CODE` varchar(32) DEFAULT NULL COMMENT '角色编码',
  `ROLE_COMMENT` varchar(256) DEFAULT NULL COMMENT '角色备注',
  `ROLE_RANGE` varchar(16) DEFAULT NULL COMMENT '角色类型 0业务角色 1授权角色',
  PRIMARY KEY (`ROLE_ID`),
  KEY `UK_APPID_ROLECODE` (`APP_ID`,`ROLE_CODE`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='系统角色表'



CREATE TABLE `sy_role_rela` (
  `USER_ID` varchar(40) NOT NULL COMMENT '账户ID',
  `ROLE_ID` varchar(40) NOT NULL COMMENT '角色ID',
  `ROLE_RANGE` varchar(1) NOT NULL COMMENT '角色类型 0业务1授权',
  PRIMARY KEY (`USER_ID`,`ROLE_ID`),
  KEY `INDEX_ROLE_ID` (`ROLE_ID`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='系统用户与角色对照关系表'

