DROP TABLE IF EXISTS `sy_dept`;
CREATE TABLE `sy_dept` (
  `dept_no` VARCHAR(16) NOT NULL COMMENT '部门编号',
  `dept_name` VARCHAR(255) NOT NULL COMMENT '部门名称',
  `org_no` VARCHAR(16) NOT NULL COMMENT '所属单位',
  `TYPE_CODE` VARCHAR(16) DEFAULT NULL COMMENT '部门类型',
  `P_DEPT_NO` VARCHAR(16) DEFAULT NULL COMMENT '上级部门',
  `DISP_SN` VARCHAR(8) DEFAULT NULL,
  PRIMARY KEY (`dept_no`),
  KEY `IDX_SYSDEPT_ORGNO` (`org_no`),
  KEY `IDX_SYSDEPT_PDEPTNO` (`P_DEPT_NO`)
) ENGINE=INNODB  DEFAULT CHARSET=utf8 COMMENT = '系统部门表';